### ISSUE TITLE
DNS only VPN

### ISSUE THREAD

**Issue by iambenmitchell** [purkylin/KingProxy#10]
Hello, I am trying to make an App like Cloudflare's 1.1.1.1 app, but with my Own DNS server. It should function the same as setting DNS on wifi settings, however, I want to be able to use it with mobile data too, thus an app is needed. Any idea how I can do this? 

I don't want to have an external vpn server, ie, changing IP. Rather, it should run locally.

**Comment by purkylin** [comment]
You should write a Network Extension for your app

**Comment by purkylin** [comment]
May be help for you.
https://www.wwdcnotes.com/notes/wwdc20/10047/

**Comment by iambenmitchell** [comment]
Hi, yes I saw that and I have it working, however it is only for iOS 14 and above. I have no idea how to write a network extension for DNS only

**Comment by purkylin** [comment]
1. Interceptors tcp request packet in tunnel,  query ip use your dns server, modify/forward your packet. This is very complicated, you should know well socket programing and tcp packet format;
2. Set dns server in tunnel, without deal with packet (Related API NEDNSSettings, not tested)

**Comment by purkylin** [comment]
NEDNSProxyManager only for iOS 11 above

**Comment by iambenmitchell** [comment]
I found this: [link](https://stackoverflow.com/questions/45508605/how-to-use-nednsproxyprovider-in-ios-11?answertab=votes#tab-top)

But I cannot get it to run, my phone asks me to add the configuration, when I press allow and enter my password, the vpn settings pane in settings is empty. Maybe because I am on iOS 14? I literally just copy pasted the code from that article. Also, I don't see where to set my DNS ip

**Comment by purkylin** [comment]
That comment said that need mdm, so you could not use the api in normal device. That should work for debug build app.
