### ISSUE TITLE
Is it possible to work with NEPacketTunnelProvider?

### ISSUE THREAD

**Issue by joeguo** [purkylin/KingProxy#9]
NeKit is too big for me.
Is it possible to work with NEPacketTunnelProvider?

Thanks

**Comment by purkylin** [comment]
It's possible. If you only focus on http protocol, you needn't do any other things. If you use tcp packet, you should wrap a tun2socks then point to it.

**Comment by joeguo** [comment]
thanks for you help. I got it.
